from ware import Ware
deine_mutter = Ware()
reis = Ware()
pesto = Ware()
reis.set_namen("Reis")
reis.set_preis("1.99")
reis.set_bestand("10")
deine_mutter.set_namen("Raphael Mutter")
deine_mutter.set_preis("0.99")
deine_mutter.set_bestand("1")
pesto.set_namen("Pesto")
pesto.set_preis("2.99")
pesto.set_bestand("5")

gestamt = reis.get_preis() + deine_mutter.get_preis() + pesto.get_preis()
print(reis.get_namen() + " kostet " + str(reis.get_preis()) + " Euro")
print(deine_mutter.get_namen() + " kostet " + str(deine_mutter.get_preis()) + " Euro")
print(pesto.get_namen() + " kostet " + str(pesto.get_preis()) + " Euro")

print("bestand von " + reis.get_namen() + " ist " + str(reis.get_bestand()))
print("bestand von " + deine_mutter.get_namen() + " ist " + str(deine_mutter.get_bestand()))
print("bestand von " + pesto.get_namen() + " ist " + str(pesto.get_bestand()))
reis.auffüllen("5")
deine_mutter.auffüllen("300")
pesto.auffüllen("100")
print("bestand von " + reis.get_namen() + " ist " + str(reis.get_bestand()))
print("bestand von " + deine_mutter.get_namen() + " ist " + str(deine_mutter.get_bestand()))
print("bestand von " + pesto.get_namen() + " ist " + str(pesto.get_bestand()))
reis.entnemen("3")
deine_mutter.entnemen("1")
pesto.entnemen("2")
print("bestand von " + reis.get_namen() + " ist " + str(reis.get_bestand()))
print("bestand von " + deine_mutter.get_namen() + " ist " + str(deine_mutter.get_bestand()))
print("bestand von " + pesto.get_namen() + " ist " + str(pesto  .get_bestand()))
print("Der Gesamtpreis beträgt von reis " + str(reis.get_bestandpreis()) + " Euro")
print("Der Gesamtpreis beträgt von deine_mutter " + str(deine_mutter.get_bestandpreis()) + " Euro")
print("Der Gesamtpreis beträgt von pesto " + str(pesto.get_bestandpreis()) + " Euro")
print("Der Gesamtpreis beträgt " + str(gestamt) + " Euro")

